# charts/prometheus/values.yaml

# --- Grafana 설정 ---
# 이 스택에 포함된 Grafana는 사용하지 않고, 나중에 별도로 배포할 것이므로 비활성화합니다.
# 이렇게 해야 리소스를 절약하고 관리를 중앙화할 수 있습니다.
grafana:
  enabled: false

# --- Alertmanager 설정 ---
# 프로메테우스 경고를 관리하고 발송하는 컴포넌트입니다.
alertmanager:
  enabled: true
  alertmanagerSpec:
    # 운영 환경에서는 Alertmanager의 상태(ex: 음소거된 경고)를 보존하기 위해
    # PersistentVolumeClaim(PVC)을 사용한 영구 저장소 설정이 필수적입니다.
    storage:
      volumeClaimTemplate:
        spec:
          # 사용하는 클러스터의 스토리지 클래스를 지정합니다. (예: gp2, gp3)
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi # Alertmanager 상태 저장은 많은 공간을 요구하지 않습니다.

# --- Prometheus 서버 설정 ---
prometheus:
  enabled: true
  # Prometheus 서버 자체에 대한 상세 설정
  prometheusSpec:
    # 고가용성을 위해 프로메테우스 서버를 2대로 실행합니다.
    # 각 서버는 독립적으로 데이터를 수집하며, 장애 발생 시 다른 서버가 서비스를 계속합니다.
    replicas: 2

    # 메트릭 데이터(시계열 데이터)를 저장할 공간 설정입니다.
    # 이것이 없으면 파드가 재시작될 때 모든 모니터링 데이터가 사라집니다. **매우 중요합니다.**
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2 # 비용과 성능을 고려하여 gp3 사용을 권장합니다.
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              # 수집하는 메트릭의 양과 보관 기간에 따라 용량을 산정해야 합니다.
              # 운영 환경에서는 최소 50Gi 이상으로 시작하는 것을 권장합니다.
              storage: 50Gi

    # Prometheus가 메트릭 데이터를 얼마나 오랫동안 보관할지 결정합니다. (기본값: 10일)
    # 기간이 길수록 더 많은 디스크 공간이 필요합니다.
    retention: 15d
    retentionSize: "" # 용량 기반으로 제한할 수도 있습니다.

    # Prometheus Operator가 어떤 ServiceMonitor를 감지할지 결정하는 라벨 셀렉터입니다.
    # 비워두면 모든 네임스페이스의 모든 ServiceMonitor를 대상으로 합니다.
    serviceMonitorSelector: {}
    # 어떤 PodMonitor를 감지할지 결정하는 라벨 셀렉터입니다.
    podMonitorSelector: {}

    # 추가적인 리소스 설정. 파드의 CPU/메모리 요청량 및 한계량을 설정합니다.
    # 클러스터 규모에 맞게 조절해야 합니다.
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1
        memory: 4Gi

# --- 기본으로 설치되는 Exporter 설정 ---
# Node Exporter: 모든 노드의 시스템 메트릭을 수집합니다. (필수)
nodeExporter:
  enabled: true

# Kube State Metrics: Kubernetes 오브젝트 상태 메트릭을 수집합니다. (필수)
kubeStateMetrics:
  enabled: true