apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: fanda-cicd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # 단일 source: Prometheus community Helm repo + values.yaml 은 같은 repo 내에서 참조
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 59.1.0
    helm:
      valueFiles:
        - ../values/prometheus.yaml  # 상대 경로로 values.yaml 지정 (아래 설명 참고)

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fanda-monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
