apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: fanda-cicd
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # 예: grafana 이후에 동기화
spec:
  project: default

  source:
    repoURL: https://github.com/simu88/cicd-test.git
    targetRevision: HEAD
    path: charts/loki-stack    # Loki가 포함된 통합 헬름 차트 경로
    helm:
      valueFiles:
        - ../../values/loki.yaml           # Loki 설정 전용 values 파일

  destination:
    server: https://kubernetes.default.svc
    namespace: fanda-monitoring             # Loki 네임스페이스, 필요시 생성

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
