apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: fanda-cicd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/simu88/cicd-test.git
    targetRevision: HEAD
    path: charts/kube-prometheus-stack       # Helm 차트 위치 지정 (복제된 차트)
    helm:
      valueFiles:
        - ../../values/prometheus.yaml  # Helm 차트 위치 기준 상대경로

  destination:
    server: https://kubernetes.default.svc
    namespace: fanda-monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true        # 추가
