apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: fanda-cicd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/simu88/cicd-test.git
    targetRevision: HEAD
    path: charts/tempo-stack
    helm:
      valueFiles:
        - ../../values/tempo.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fanda-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
